version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/deploy"
      - "/.github/actions/test"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directories:
      - "/humble"
      - "/iron"
      - "/jazzy"
      - "/rolling"
    schedule:
      interval: "daily"
