version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/humble"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/iron"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/rolling"
    schedule:
      interval: "daily"