name: Build and Test (Humble)
on:
  pull_request:
    branches:
      - master
    paths:
      - "humble/**"
      - ".github/workflows/test-humble.yml"
      - ".github/actions/test/action.yml"
  schedule:
    - cron: "0 2 * * 0" # Weekly on Sundays at 02:00
  workflow_dispatch:

env:
  DOCKER_USERNAME: tiryoh
  DOCKER_IMAGENAME: ros2-desktop-vnc

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-22.04
          - arch: arm64
            runner: ubuntu-22.04-arm
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true
      - uses: ./.github/actions/test
        with:
          ros-distro: humble
          arch: ${{ matrix.arch }}
