name: Build and Test (Foxy)
on:
  pull_request:
    branches:
      - master
    paths:
      - "foxy/**"
      - ".github/workflows/test-foxy.yml"
      - ".github/actions/test/action.yml"
  schedule:
    - cron: "0 2 * * 0" # Weekly on Sundays at 02:00
  workflow_dispatch:

env:
  DOCKER_USERNAME: tiryoh
  DOCKER_IMAGENAME: ros2-desktop-vnc

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64, amd64]
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: ./.github/actions/test
        with:
          ros-distro: foxy
          arch: ${{ matrix.arch }}
